### PR TITLE
Added format for GUID.

### PR DESCRIPTION
**Pull request by vivane**

### CODE REVIEW

**Comment by ikr** [comment]
Thanks for the MR @vivane! I'd suggest however dropping the optional "{...}" wrapping. Doesn't seem to be a part of [standard string representation](https://en.wikipedia.org/wiki/Universally_unique_identifier).

**Comment by vivane** [comment]
I added braces as optional as I saw it at https://en.wikipedia.org/wiki/Globally_unique_identifier... Do you still suggest it to be removed?

**Comment by ikr** [comment]
Ah, I see it now. Thanks. Will merge & publish a new version shortly.

**Comment by ikr** [comment]
v2.1.0 is up

**Comment by vivane** [comment]
Thanks.

**Pull request merged**
