### PR TITLE
Universal Module Definition (UMD) support is included.

### PR DESCRIPTION
**Pull request by DanisaurioRex**

### CODE REVIEW

**Comment by ikr** [comment]
Oh wow, that's _super_ intrusive. I'd rather not introduce all that noisy boilerplate.

Could you please explain me in a greater detail, what problem you're actually solving? If a bare npm module is not enough, and you absolutely need to package tv4-formats as an UMD, I'd consider a code generation solution for this.

**Comment by DanisaurioRex** [comment]
Well, I want to solve the issue https://github.com/chaijs/chai-json-schema/issues/31, and I need to implement correctly the tv4 formats in the Chai-json-schema project. The problem is that in this other project the MDU has been implemented, and the formats tv4 can not be introduced. Excuse me if I am not doing it correctly and please explain to me if there is another way to do it.

Thank you

**Comment by ikr** [comment]
I don't think you need tv4-formats in UMD for that. Instead, you could

```
const formats = require('tv4-formats')
```

and then

```
chai.tv4.addFormat(formats)
```

after which, tv4 will start validating the string values' formats. Are you using chai-json-schema in the browser, or are you running the assertions in Node?

**Comment by DanisaurioRex** [comment]
The asserts are running in the 3 ways `/*jshint -W003*/
  if (typeof require === 'function' && typeof exports === 'object' && typeof module === 'object') {
    // NodeJS
    getPayload(require('chai'), require('../index'));
  } else if (typeof define === 'function' && define.amd) {
    // AMD
    define([
      'chai',
      'chai-json-schema',
    ], function (chai, plugin) {
      return getPayload(chai, plugin);
    });
  } else {
    // Other environment (usually <script> tag): plug in to global chai instance directly.
    return getPayload(window.chai, null);
  }`

**Comment by ikr** [comment]
Daniel, I'm sorry, I won't introduce that massive amount of boilerplate, touching every single file of this little module. I'm afraid you have to solve your problem differently. A fork is always an option ;-)

**Comment by DanisaurioRex** [comment]
Ok, if that's your "Open Source philosophy" there is no problem. I recommend you read a little about UMD and about the standardization of modules, it is not boilerplate code. Here's a good article for you: https://addyosmani.com/writing-modular-js/. Good luck with your project.

**Comment by ikr** [comment]
Daniel, the code is MIT-licensed. I quote:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.

But you are free to do basically whatever with it. Being absolutely accommodating or dominating the world with this little module is not within my goals. 

Please don't take that personally! I just don't have time to get into the details, and maintain the UMD compatibility right now.

**Pull request closed without merging**
